# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stkoe_pb2 as stkoe__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stkoe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StkoeServiceStub:
    """stkoe 数据服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/stkoe.StkoeService/Execute',
                request_serializer=stkoe__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=stkoe__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/stkoe.StkoeService/SubmitTask',
                request_serializer=stkoe__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=stkoe__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.SubscribeTask = channel.unary_stream(
                '/stkoe.StkoeService/SubscribeTask',
                request_serializer=stkoe__pb2.SubscribeTaskRequest.SerializeToString,
                response_deserializer=stkoe__pb2.SubscribeTaskResponse.FromString,
                _registered_method=True)
        self.TaskControl = channel.unary_unary(
                '/stkoe.StkoeService/TaskControl',
                request_serializer=stkoe__pb2.TaskControlRequest.SerializeToString,
                response_deserializer=stkoe__pb2.TaskControlResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/stkoe.StkoeService/Health',
                request_serializer=stkoe__pb2.HealthRequest.SerializeToString,
                response_deserializer=stkoe__pb2.HealthResponse.FromString,
                _registered_method=True)


class StkoeServiceServicer:
    """stkoe 数据服务
    """

    def Execute(self, request, context):
        """命令执行：元数据/列表/状态等小结果 JSON，或表格数据 Arrow IPC；
        服务端流式返回，首条恒为 DataHeader
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """后台任务：提交长任务（物化/统计/公式）立即返回 task_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTask(self, request, context):
        """任务订阅：按 task_id 订阅任务事件流（进度/日志/状态/结果）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskControl(self, request, context):
        """任务操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """服务存活探活 + 版本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StkoeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=stkoe__pb2.ExecuteRequest.FromString,
                    response_serializer=stkoe__pb2.ExecuteResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=stkoe__pb2.SubmitTaskRequest.FromString,
                    response_serializer=stkoe__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'SubscribeTask': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTask,
                    request_deserializer=stkoe__pb2.SubscribeTaskRequest.FromString,
                    response_serializer=stkoe__pb2.SubscribeTaskResponse.SerializeToString,
            ),
            'TaskControl': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskControl,
                    request_deserializer=stkoe__pb2.TaskControlRequest.FromString,
                    response_serializer=stkoe__pb2.TaskControlResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=stkoe__pb2.HealthRequest.FromString,
                    response_serializer=stkoe__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stkoe.StkoeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stkoe.StkoeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StkoeService:
    """stkoe 数据服务
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stkoe.StkoeService/Execute',
            stkoe__pb2.ExecuteRequest.SerializeToString,
            stkoe__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stkoe.StkoeService/SubmitTask',
            stkoe__pb2.SubmitTaskRequest.SerializeToString,
            stkoe__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stkoe.StkoeService/SubscribeTask',
            stkoe__pb2.SubscribeTaskRequest.SerializeToString,
            stkoe__pb2.SubscribeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stkoe.StkoeService/TaskControl',
            stkoe__pb2.TaskControlRequest.SerializeToString,
            stkoe__pb2.TaskControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stkoe.StkoeService/Health',
            stkoe__pb2.HealthRequest.SerializeToString,
            stkoe__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
