# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stkoe.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'stkoe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstkoe.proto\x12\x05stkoe\"+\n\x0e\x45xecuteRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"e\n\x0f\x45xecuteResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x10\n\x08json_out\x18\x03 \x01(\t\x12\r\n\x05table\x18\x04 \x01(\x0c\x12\x14\n\x0ctable_schema\x18\x05 \x01(\t\"t\n\rSelectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x03 \x03(\t\x12\r\n\x05where\x18\x04 \x01(\t\x12\x11\n\tpartition\x18\x05 \x01(\t\x12\x14\n\x0cinclude_tool\x18\x06 \x01(\x08\"S\n\x0eSelectResponse\x12\x0b\n\x03ipc\x18\x01 \x01(\x0c\x12\x13\n\x0bschema_json\x18\x02 \x01(\t\x12\x10\n\x08num_rows\x18\x03 \x01(\x03\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\x7f\n\x0cStkoeService\x12\x38\n\x07\x45xecute\x12\x15.stkoe.ExecuteRequest\x1a\x16.stkoe.ExecuteResponse\x12\x35\n\x06Select\x12\x14.stkoe.SelectRequest\x1a\x15.stkoe.SelectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stkoe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=22
  _globals['_EXECUTEREQUEST']._serialized_end=65
  _globals['_EXECUTERESPONSE']._serialized_start=67
  _globals['_EXECUTERESPONSE']._serialized_end=168
  _globals['_SELECTREQUEST']._serialized_start=170
  _globals['_SELECTREQUEST']._serialized_end=286
  _globals['_SELECTRESPONSE']._serialized_start=288
  _globals['_SELECTRESPONSE']._serialized_end=371
  _globals['_STKOESERVICE']._serialized_start=373
  _globals['_STKOESERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
