# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stkoe_pb2 as stkoe__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stkoe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StkoeServiceStub:
    """stkoe 数据服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/stkoe.StkoeService/Execute',
                request_serializer=stkoe__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=stkoe__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/stkoe.StkoeService/Select',
                request_serializer=stkoe__pb2.SelectRequest.SerializeToString,
                response_deserializer=stkoe__pb2.SelectResponse.FromString,
                _registered_method=True)


class StkoeServiceServicer:
    """stkoe 数据服务
    """

    def Execute(self, request, context):
        """通用命令执行：元数据/列表/状态等小结果，返回 JSON
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """表格查询：table/dataset 数据读取，返回 Arrow IPC 序列化帧
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StkoeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=stkoe__pb2.ExecuteRequest.FromString,
                    response_serializer=stkoe__pb2.ExecuteResponse.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=stkoe__pb2.SelectRequest.FromString,
                    response_serializer=stkoe__pb2.SelectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stkoe.StkoeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stkoe.StkoeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StkoeService:
    """stkoe 数据服务
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stkoe.StkoeService/Execute',
            stkoe__pb2.ExecuteRequest.SerializeToString,
            stkoe__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stkoe.StkoeService/Select',
            stkoe__pb2.SelectRequest.SerializeToString,
            stkoe__pb2.SelectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
